namespace: bouncmpe
name: automated
description: ""
repository: "https://github.com/bouncmpe/automated"
version: 0.8.1
readme: README.md
authors:
  - Dogan Ulus <dogan.ulus@boun.edu.tr>
dependencies:
  community.vmware: ">=3.0.0"
  community.general: ">=6.0.0"
