- name: Manage user quotas
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ automated_config_users }}"
  loop_control:
    loop_var: user
  when: automated_config_home_enable_quotas
