- name: Install dependencies
  ansible.builtin.package:
    name:
      - quota
      - linux-image-extra-virtual # Kernel modules to implemet quotas
    state: present
  when: automated_config_home_enable_quotas

- name: Mount up device where HOME resides
  ansible.posix.mount:
    path: "{{ automated_config_home_mount_point }}"
    src: "{{ automated_config_home_mount_device }}"
    fstype: "{{ automated_config_home_mount_fstype }}"
    opts: "{{ automated_config_home_mount_options }}"
    state: mounted
  when: automated_config_home_enable_quotas

- name: Remount a mounted volume
  ansible.posix.mount:
    path: "{{ automated_config_home_mount_point }}"
    state: remounted
  when: automated_config_home_enable_quotas

- name: Initialize user quotas
  ansible.builtin.command:
    cmd: quotacheck -um "{{ automated_config_home_mount_point }}"
    creates: "{{(automated_config_home_mount_point , 'aquota.user') | path_join }}"
  when: automated_config_home_enable_quotas

- name: Initialize group quotas
  ansible.builtin.command:
    cmd: quotacheck -gm "{{ automated_config_home_mount_point }}"
    creates: "{{(automated_config_home_mount_point , 'aquota.group') | path_join }}"
  when: automated_config_home_enable_quotas
  
- name: Query user quota info
  ansible.builtin.command: 
    cmd: quotaon -p --user "{{ automated_config_home_mount_point }}"
  register: user_quota_query_result
  ignore_errors: true
    
- name: Test user quota is ON
  ansible.builtin.set_fact:
    user_quota_on: "{{ user_quota_query_result | regex_search('is on') }}"

- name: Enable user quota if not enabled
  ansible.builtin.shell:
    cmd: quotaon -v --user "{{ automated_config_home_mount_point }}"
  when: automated_config_home_enable_quotas and user_quota_on == ""
  
- name: Query group quota info
  ansible.builtin.command: 
    cmd: quotaon -p --group "{{ automated_config_home_mount_point }}"
  register: group_quota_query_result
  ignore_errors: true
    
- name: Test group quota is ON
  ansible.builtin.set_fact:
    group_quota_on: "{{ group_quota_query_result | regex_search('is on') }}"

- name: Enable group quota if not enabled
  ansible.builtin.shell:
    cmd: quotaon -v --group "{{ automated_config_home_mount_point }}"
  when: automated_config_home_enable_quotas and group_quota_on == ""

- name: Manage user quotas
  ansible.builtin.include_tasks:
    file: single_user.yml
  loop: "{{ automated_config_users }}"
  loop_control:
    loop_var: user
  when: automated_config_home_enable_quotas
