---
- name: Deploy virtual guests using libvirt
  ansible.builtin.include_tasks:
    file: single.yml
  loop: "{{ query('inventory_hostnames', 'virtual_guest') | map ('extract', hostvars) | list }}"
  loop_control:
    label: "{{ guest.inventory_hostname }}"
    loop_var: guest

- name: Clean up temporary cloudinit files
  ansible.builtin.file:
    path: "{{ virtual_guest_cloudinit_cache_path }}"
    state: absent
